// 44 种组件的最小合法样本(与 ../lib.mjs 同一份内容,单独放一份是为了避免
// 在 playwright 进程里引入 lib.mjs 的 uncaughtException 处理器)。
export const SAMPLES = {
  text: { type: 'text', content: 'hi' },
  row: { type: 'row', items: [{ type: 'text', content: 'a' }] },
  col: { type: 'col', items: [{ type: 'text', content: 'a' }] },
  grid: { type: 'grid', items: [{ type: 'text', content: 'a' }], cols: 2 },
  card: { type: 'card', items: [{ type: 'text', content: 'a' }] },
  divider: { type: 'divider' },
  spacer: { type: 'spacer' },
  stat: { type: 'stat', label: 'L', value: '42' },
  badge: { type: 'badge', label: 'B' },
  progress: { type: 'progress', label: 'P', value: 50 },
  avatar: { type: 'avatar', name: 'Ann' },
  list: { type: 'list', items: ['a', 'b'] },
  table: { type: 'table', columns: ['c1'], rows: [['1']] },
  keyvalue: { type: 'keyvalue', pairs: [{ key: 'k', value: 'v' }] },
  timeline: { type: 'timeline', items: [{ title: 't' }] },
  steps: { type: 'steps', steps: [{ title: 's' }] },
  breadcrumb: { type: 'breadcrumb', items: ['a'] },
  'file-tree': { type: 'file-tree', items: [{ name: 'a.txt', type: 'file' }] },
  callout: { type: 'callout', content: 'c' },
  code: { type: 'code', code: 'x=1', lang: 'js' },
  json: { type: 'json', value: { a: 1 } },
  diff: { type: 'diff', diffs: [{ path: 'p.txt', oldText: null, newText: 'n' }] },
  link: { type: 'link', label: 'L', href: 'https://example.com' },
  audio: { type: 'audio', src: '/api/files/a.mp3' },
  video: { type: 'video', src: '/api/files/a.mp4' },
  chart: { type: 'chart', data: [{ label: 'a', value: 1 }] },
  plot: { type: 'plot', series: [{ expr: 'sin(x)' }] },
  echart: { type: 'echart', data: [{ label: 'a', value: 1 }] },
  button: { type: 'button', label: 'B', action: 'go' },
  input: { type: 'input', label: 'L' },
  textarea: { type: 'textarea', label: 'L' },
  select: { type: 'select', options: ['a', 'b'] },
  radio: { type: 'radio', options: ['a', 'b'] },
  checkbox: { type: 'checkbox', label: 'L' },
  switch: { type: 'switch', label: 'L' },
  slider: { type: 'slider', label: 'L' },
  submit: { type: 'submit', label: '交卷' },
  quiz: { type: 'quiz', question: 'q', options: [{ label: 'a', correct: true }] },
  tabs: { type: 'tabs', tabs: [{ label: 't', items: [{ type: 'text', content: 'x' }] }] },
  accordion: { type: 'accordion', items: [{ title: 't', items: [{ type: 'text', content: 'x' }] }] },
  copy: { type: 'copy', text: 'x' },
  mermaid: { type: 'mermaid', code: 'flowchart TD\n  A-->B' },
  diagram: { type: 'diagram', kind: 'architecture', nodes: [{ label: 'A', type: 'focal' }] },
  scene3d: { type: 'scene3d', meshes: [{ shape: 'box' }] },
};
export const ALL_TYPES = Object.keys(SAMPLES);
